schema_version: "1.0"
mcp_name: "Pakistani Law MCP"
jurisdiction: "PK"

sources:
  - name: "Pakistan Code"
    authority: "Pakistan Code"
    official_portal: "http://www.pakistancode.gov.pk"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "weekly"
    last_ingested: "2026-02-21"
    license_or_terms:
      type: "Government Open Data"
      url: "http://www.pakistancode.gov.pk"
      summary: "Official legislative texts are public domain"
    coverage:
      scope: "Data protection, cybersecurity, e-commerce, criminal law cyber provisions"
      limitations: "AI-generated seed data; full official ingestion pending"
    languages:
      - "en"
      - "ur"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "2026-02-21"
