schema_version: "1.0"
mcp_name: "Pakistani Law MCP"
jurisdiction: "PK"

sources:
  - name: "The Pakistan Code"
    authority: "Ministry of Law and Justice, Government of Pakistan (Laws of Pakistan Cell)"
    official_portal: "https://pakistancode.gov.pk/english/index.php"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "unknown"
    license_or_terms:
      type: "government_terms"
      url: "https://pakistancode.gov.pk/english/Xki72HF.php"
      summary: "Portal disclaimer states content is for information purposes and users should refer to Gazette notifications."
    coverage:
      scope: "Federal laws listed on Pakistan Code with law-level pages and downloadable PDF texts."
      limitations: "Complete law text is served as embedded/downloadable PDF. The article-text AJAX endpoint (UY2FqaJw2.php) returns a WAF block page from this environment, so machine-readable section extraction was not feasible."
    languages:
      - "en"
      - "ur"

data_freshness:
  automated_checks: false
  check_frequency: "manual"
  last_verified: "2026-02-21"
