schema_version: "1.0"
mcp_name: "Pakistani Law MCP"
jurisdiction: "PK"

sources:
  - name: "The Pakistan Code"
    authority: "Ministry of Law and Justice, Government of Pakistan (Laws of Pakistan Cell)"
    official_portal: "https://pakistancode.gov.pk/english/index.php"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "unknown"
    license_or_terms:
      type: "government_terms"
      url: "https://pakistancode.gov.pk/english/Xki72HF.php"
      summary: "Portal disclaimer states content is for information purposes and users should refer to Gazette notifications."
    coverage:
      scope: "Federal laws listed on Pakistan Code with law-level pages and downloadable complete-law PDFs (A-Z index crawl)."
      limitations: "As of 2026-02-21, 1030 laws were indexed; 1018 were ingestible. 12 entries had broken PDF URLs or zero extractable PDF text. Structured article endpoint access is restricted from this environment."
    languages:
      - "en"
      - "ur"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "2026-02-21"
